name: Validate Secrets

on:
  push:
    branches:
      - main

jobs:
  validate-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print secrets (safely)
      run: |
        echo "EC2_HOST is set"
        echo "EC2_USER is set"
        echo "EC2_PASSWORD is set"
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
